apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: exceptional-moth-python 
  janus-idp.io/tekton: exceptional-moth-python
  backstage.io/kubernetes-id: exceptional-moth-python
  backstage.io/kubernetes-namespace: rhtap-demo 
  app.kubernetes.io/part-of: exceptional-moth-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  